### ISSUE TITLE
Steuernummer im Shop hinzufügen

### ISSUE THREAD

**Issue by PMD3VSolution** [PMD3VSolution/TronEuropeShopTroubleshooting#6]

**Comment by j4ckse7en** [comment]
Wenn ichs richtig im Kopf habe nehmen wir vorläufig die Steuernummer von Dirks Firma.

**Comment by catchflex90** [comment]
vat id ist jetzt hinterlegt in der Fußzeile der Rechnung

**Comment by PMD3VSolution** [comment]
super, dann kann der fall geschlossen werden
